name: CI

on:
  push:
    branches: [main, dev, work]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install black flake8 isort pylint pytest

      - name: Lint with Black
        run: |
          black --check .

      - name: Lint with Flake8
        run: |
          flake8

      - name: Lint with Isort
        run: |
          isort --check-only .

      - name: Lint with Pylint
        run: |
          pylint src tests

      - name: Run Pytest
        run: |
          pytest -q
